# Generated by Django 4.0.3 on 2023-04-22 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_portal', '0004_alter_vehicles_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicles',
            old_name='photo',
            new_name='image',
        ),
    ]
